<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="1.8.2" />
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\PeterJuhasz.Text.Html\PeterJuhasz.Text.Html.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\PeterJuhasz.Text.Html.Benchmarks\Samples\*.html" Link="Samples\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
